name: Compile Kernel

on:
  workflow_dispatch:
    inputs:
      brand:
        description: "Brand: Select your brand"
        required: true
        type: choice
        default: oneplus
        options:
          - Manual-Type
          - oneplus
          - xiaomi
          - sony

      brand_manual:
        description: "Brand-Manual: If selected Manual-Type in previous options, manually type ur brand"
        required: false
        type: string
        default: ""

      soc:
        description: "SOC: Type your soc"
        required: true
        type: string
        default: "sm8550"

      clang_version:
        description: "Clang-Version: Select the clang version of ur kernel"
        required: true
        type: choice
        default: clang-r563880c
        options:
          - clang-r416183b1
          - clang-r450784d
          - clang-r487747c
          - clang-r536225
          - clang-r547379
          - clang-r563880c
          
      kernel_source:
        description: "Kernel-Source: Kernel repo's org/user on github"
        required: true
        type: choice
        default: LineageOS
        options:
          - Manual-Type
          - LineageOS
          - YAAP
          - PixelOS-Devices
          - PixelExperience-Devices
          - VoltageOS-Devices
          - BlissRoms-Devices
          - AxionAOSP-devices
          - AlphaDroid-devices
          - DerpFest-Devices
          - MistOS-Devices
          - crdroidandroid
          - Evolution-X-Devices
          - Infinity-X-Devices
          - OnePlus12R-development
          - complex-lllf
          - ppanzenboeck

      kernel_source_manual:
        description: "Kernel-Source-Manual: If u selected Manual-Type in previous options, manually type ur repo's org/user on github here."
        required: false
        type: string
        default: ""

      kernel_source_format:
        description: "Source-Format: Select ur kernel source format(1 for los etc. 2 for yaap etc.)(keep default if u dont know)"
        required: true
        type: choice
        default: android_kernel
        options:
          - android_kernel
          - kernel

      kernel_branch:
        description: "Kernel-Branch: such as lineage-23.2 sixteen-qpr1 etc."
        required: true
        type: string
        default: "lineage-23.2"
        
      kernel_configs:
        description: "Kernel-Configs: Select ur kernel configs(Use Manual-Type to custom it)"
        required: true
        type: choice
        default: oplus-sm8550-los
        options:
          - Manual-Type
          - oplus-sdm845-los
          - oplus-sm8150-los
          - oplus-sm8150-yaap
          - oplus-sm8250-los
          - oplus-sm8350-los
          - oplus-sm8550-los
          - oplus-sm8650-los
          - oplus-sm8750-los

      kernel_configs_manual:
        description: "Kernel-Configs-Manual: If u selected Manual-Type in previous options, manually type ur kernel configs here."
        required: false
        type: string
        default: ""

      ksu_type:
        description: "KSU: KernelSU Version"
        required: true
        type: choice
        default: None
        options:
          - None
          - Official-KernelSU
          - KernelSU-Next
          - KernelSU-Next-with-susfs
          - KowSU
          - KernelSU-by-xx
          - ReSukiSU
          - ReSukiSU-with-susfs

      susfs-gki:
        description: "SUSFS-GKI: select ur kernel version(for gki)"
        required: true
        type: choice
        default: None
        options:
          - None
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
          - android16-6.12

      susfs-nongki:
        description: "SUSFS-NONGKI: select ur kernel version(for nongki)"
        required: true
        type: choice
        default: None
        options:
          - None
          - "4.9"
          - "4.14"
          - "4.19"
          - "5.4"

      droidspaces:
        description: "DroidSpaces: Enable DroidSpaces"
        required: true
        type: choice
        default: None
        options:
          - None
          - "6.12"
          - 5.15-6.6
          - "5.10"
          - "5.4"
          - 4.14-4.19
          - 4.4-4.9
          - "3.18"

      has_modules_repo:
        description: "Has-Modules-Repo: Enable this ur kernel has modules repo(mostly for gki 2.0)"
        required: true
        type: boolean
        default: true

      enable_tmpfs-xattr:
        description: "TMPFS_XATTR: U can enable this if ur kernel has no CONFIG_TMPFS_XATTR=y"
        required: true
        type: boolean
        default: false

      enable_gcc:
        description: "Enable-GCC: Enable the GCC support(mostly for 4.14 and below)"
        required: true
        type: boolean
        default: false
      
      enable_gcc_32bits:
        description: "Enable-GCC-32Bits: Enable the 32Bits GCC support(mostly for 4.9 and below)"
        required: true
        type: boolean
        default: false

      fuck_modules_sig_protect:
        description: "Fuck-Modules-Sig-Protect: FUCK MODULES SIG Protect(maybe need for 6.1)"
        required: true
        type: boolean
        default: false

      fuck_werror:
        description: "Fuck-Werror: FUCK WERROR IN CONFIGS(by disable WERROR and CC_WERROR)"
        required: true
        type: boolean
        default: false

      enable_my_own_susfs_patch:
        description: "Fuck susfs: apply patches in patches dir about susfs"
        required: true
        type: boolean
        default: false

jobs:
  Kernel_CI:
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      checks: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
          bc bison flex \
          libssl-dev \
          libelf-dev \
          libdw-dev \
          build-essential \
          lz4 \
          git \
          python3 \
          curl \
          dwarves \
          cpio \
          gcc-aarch64-linux-gnu

      - name: Save options
        run: |
          {
            echo "brand:${{ inputs.brand }}"
            echo "brand_manual:${{ inputs.brand_manual }}"
            echo "soc:${{ inputs.soc }}"
            echo "clang_version:${{ inputs.clang_version }}"
            echo "kernel_source:${{ inputs.kernel_source }}"
            echo "kernel_source_manual:${{ inputs.kernel_source_manual }}"
            echo "kernel_source_format:${{ inputs.kernel_source_format }}"
            echo "kernel_branch:${{ inputs.kernel_branch }}"
            echo "kernel_configs:${{ inputs.kernel_configs }}"
            echo "kernel_configs_manual:${{ inputs.kernel_configs_manual }}"
            echo "ksu_type:${{ inputs.ksu_type }}"
            echo "susfs-gki:${{ inputs['susfs-gki'] }}"
            echo "susfs-nongki:${{ inputs.susfs-nongki }}"
            echo "droidspaces:${{ inputs.droidspaces }}"
            echo "has_modules_repo:${{ inputs.has_modules_repo }}"
            echo "enable_tmpfs-xattr:${{ inputs['enable_tmpfs-xattr'] }}"
            echo "enable_gcc:${{ inputs.enable_gcc }}"
            echo "enable_gcc_32bits:${{ inputs.enable_gcc_32bits }}"
            echo "fuck_modules_sig_protect:${{ inputs.fuck_modules_sig_protect }}"
            echo "fuck_werror:${{ inputs.fuck_werror }}"
            echo "enable_my_own_susfs_patch:${{ inputs.enable_my_own_susfs_patch }}"
          } | tee -a options.txt

      - name: Setup Git Auth
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Clone Kernel Source
        run: |
          if [[ "${{ inputs.brand }}" == "Manual-Type" ]]; then
            brand="${{ inputs.brand_manual }}"
          else
            brand="${{ inputs.brand }}"
          fi

          if [[ "${{ inputs.kernel_source }}" == "Manual-Type" ]]; then
            source="${{ inputs.kernel_source_manual }}"
          else
            source="${{ inputs.kernel_source }}"
          fi

          git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${source}/${{ inputs.kernel_source_format }}_${brand}_${{ inputs.soc }}.git ${{ inputs.soc }} || exit 1

          if [[ "${{ inputs.has_modules_repo }}" == "true" ]]; then
            git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${source}/${{ inputs.kernel_source_format }}_${brand}_${{ inputs.soc }}-modules.git ${{ inputs.soc }}-modules || exit 1
          fi

      - name: Download AOSP Clang
        run: |
          case "${{ inputs.clang_version }}" in
            "clang-r416183b1")
              curl -fL -o clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-qpr3-release/clang-r416183b1.tar.gz || exit 1
              ;;
            "clang-r450784d")
              curl -fL -o clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android13-qpr3-release/clang-r450784d.tar.gz || exit 1
              ;;
            "clang-r487747c")
              curl -fL -o clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android14-qpr3-release/clang-r487747c.tar.gz || exit 1
              ;;
            "clang-r536225")
              curl -fL -o clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android15-qpr2-release/clang-r536225.tar.gz || exit 1
              ;;
            "clang-r547379")
              curl -fL -o clang.tar.gz https://android.googlesource.com/platform/prebuilts/c
